In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import tensorflow_datasets as tfds
import tensorflow as tf

import time
import numpy as np
import matplotlib.pyplot as plt

from ut_model import *
from data_pipeline import input_fn

In [3]:
tf.__version__

'2.1.0'

In [4]:
data_dir = "/media/akanyaani/Disk2/git_repo/test_data"

In [5]:
train_dataset, test_dataset = input_fn(batch_size=16)

#train_dataset = np.random.randint(low=0,high=30000,size=(10,32, 48))

In [16]:
for i, j in train_dataset:
    print(i)
    print(j)
    break

tf.Tensor(
[[30138    53    57 13437     2 30139     0     0]
 [30138     6    26  1068    38  2205   441 30139]
 [30138  1283   123   312  1361     2 30139     0]
 [30138    31   179     2 30139     0     0     0]
 [30138    31   481     1    11  1933     2 30139]
 [30138  9523 29990     2 30139     0     0     0]
 [30138   122   927    32 14524     2 30139     0]
 [30138    95   105    70  1339     2 30139     0]
 [30138     6   401     9  2935     2 30139     0]
 [30138  2928 19963   147  3076     2 30139     0]
 [30138   573 29927    14 22001 26322     2 30139]
 [30138    49    10 13792 29914  1247   441 30139]
 [30138     6   101     3  1191     2 30139     0]
 [30138  3632    38 17718  3565     2 30139     0]
 [30138    69    97   151 30139     0     0     0]
 [30138   179     2 30139     0     0     0     0]], shape=(16, 8), dtype=int64)
tf.Tensor(
[[28543    17    20    34  8844     2 28544     0]
 [28543     4    11   629    42  4206     2 28544]
 [28543  1569    21  2711     

In [17]:
target_input = j[:, :-1]
target_output = j[:, 1:]

In [19]:
target_input

<tf.Tensor: shape=(16, 7), dtype=int64, numpy=
array([[28543,    17,    20,    34,  8844,     2, 28544],
       [28543,     4,    11,   629,    42,  4206,     2],
       [28543,  1569,    21,  2711,     2, 28544,     0],
       [28543,   146,    15,    65,   338,     2, 28544],
       [28543,    65,   414,    38,     3,  1676,     2],
       [28543,  8560,     2, 28544,     0,     0,     0],
       [28543,    54,  1216,    22, 16468,     2, 28544],
       [28543,   115,    15,    30,   174,     2, 28544],
       [28543,     4,    15,   103,     7,  2010,     2],
       [28543,    25,  3903,   264,   103,  3558,     2],
       [28543,    19,     8,    12,   184, 19725,     2],
       [28543,    17,    20,    47,   482, 16865,     2],
       [28543,     4,    62,     8,    41,  2949,     2],
       [28543,  3438,    55, 15733,     2, 28544,     0],
       [28543,    94,   128,   177, 28544,     0,     0],
       [28543,   146,    48,     2, 28544,     0,     0]])>

In [20]:
target_output

<tf.Tensor: shape=(16, 7), dtype=int64, numpy=
array([[   17,    20,    34,  8844,     2, 28544,     0],
       [    4,    11,   629,    42,  4206,     2, 28544],
       [ 1569,    21,  2711,     2, 28544,     0,     0],
       [  146,    15,    65,   338,     2, 28544,     0],
       [   65,   414,    38,     3,  1676,     2, 28544],
       [ 8560,     2, 28544,     0,     0,     0,     0],
       [   54,  1216,    22, 16468,     2, 28544,     0],
       [  115,    15,    30,   174,     2, 28544,     0],
       [    4,    15,   103,     7,  2010,     2, 28544],
       [   25,  3903,   264,   103,  3558,     2, 28544],
       [   19,     8,    12,   184, 19725,     2, 28544],
       [   17,    20,    47,   482, 16865,     2, 28544],
       [    4,    62,     8,    41,  2949,     2, 28544],
       [ 3438,    55, 15733,     2, 28544,     0,     0],
       [   94,   128,   177, 28544,     0,     0,     0],
       [  146,    48,     2, 28544,     0,     0,     0]])>

In [7]:
model = UTModel(4,
                128,
                4,
                512,
                32,
                optimizer="adam",
                learning_rate=3e-5)

model.mirrored_strategy = None

In [8]:
model.create_optimizer()
model.create_checkpoint_manager(data_dir)
model.create_summary_writer(data_dir)

Initializing model from scratch..........


(<tensorflow.python.ops.summary_ops_v2.ResourceSummaryWriter at 0x7f553c59c950>,
 <tensorflow.python.ops.summary_ops_v2.ResourceSummaryWriter at 0x7f553c2d8090>)

In [ ]:
model.fit([train_dataset, train_dataset])

(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.786634, shape=(), dtype=float32)
Step 0 Train_Loss 8.7866 Train_Accuracy 0.3048
Saving checkpoint for step 0 at /media/akanyaani/Disk2/git_repo/test_data/ckpt-3
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.700932, shape=(), dtype=float32)



Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.550935, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.631401, shape=(), dtype=float32)
Step 20 Train_Loss 8.6314 Train_Accuracy 0.3107
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............


Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.551439, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.658491, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.610163, shape=(), dtype=float32)
Step 40 Tr

Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.45537, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.439974, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder C

(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.384392, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.285012, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Deco

Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.220369, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.149805, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.167004, shape=(), dtype=float32)
(16, 8)
(1

(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.162461, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.168747, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Deco

Mini Batch Loss :-  tf.Tensor(8.188339, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.993919, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(8.095787, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Execut

(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.9051585, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.940745, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Dec

Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.819454, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.7399564, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder

Executing time
Mini Batch Loss :-  tf.Tensor(7.6749196, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.729528, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.767827, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16

Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.5364375, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.68052, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf

Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.4729605, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.210969, shape=(), dtype=float32)
(15, 8)
(15, 8)
Final encoder embedding :-  (15, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (15, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Cal

Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.2569685, shape=(), dtype=float32)
Step 250 Train_Loss 7.2570 Train_Accuracy 0.3333
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.327194, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...

Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.3695827, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.2442245, shape=(), dtype=float32)
Step 270 Train_Loss 7.2442 Train_Accuracy 0.3019
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call..

Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.183309, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.307828, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call

Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.9426727, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.0630054, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decode

Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(7.096487, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.939274, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call


Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.9500484, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.81664, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...........

(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.914667, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.7041564, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Dec


Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.7664223, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.8282533, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call.........

Mini Batch Loss :-  tf.Tensor(6.5495214, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.534862, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.701703, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Execu

(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.4727516, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.663714, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Dec

Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.2015452, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.1508675, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.303796, shape=(), dtype=float32)
(16, 8)



Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.362753, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.465424, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...........

Step 480 Train_Loss 6.2007 Train_Accuracy 0.2981
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.4513702, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.3888426, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Execu

Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.1936016, shape=(), dtype=float32)
Step 500 Train_Loss 6.1936 Train_Accuracy 0.3028
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.033869, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...

Mini Batch Loss :-  tf.Tensor(5.819628, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.039547, shape=(), dtype=float32)
Step 520 Train_Loss 6.0395 Train_Accuracy 0.2909
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(6.081635, shape=(), dtype=float32)
(16, 8)
(16, 8

In [ ]:
a = tf.constant([[1]], tf.int32)

In [ ]:
tf.tile(a, [32, 10])