In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import tensorflow_datasets as tfds
import tensorflow as tf

import time
import numpy as np
import matplotlib.pyplot as plt

from ut_model import *
from data_pipeline import input_fn

In [3]:
tf.__version__

'2.1.0'

In [4]:
data_dir = "/media/akanyaani/Disk2/git_repo/test_data"

In [5]:
train_dataset, test_dataset = input_fn(batch_size=16)

#train_dataset = np.random.randint(low=0,high=30000,size=(10,32, 48))

In [6]:
for i, j in train_dataset:
    print(i)
    print(j)
    break

tf.Tensor(
[[30138    12    53  1653 15501     2 30139     0]
 [30138    49    10  2360     2 30139     0     0]
 [30138  9990    12 10816 29991     2 30139     0]
 [30138    72     7     5   642    28 30139     0]
 [30138   372    32    17   204 15506    28 30139]
 [30138   969     3  1131     2 30139     0     0]
 [30138   333     2 30139     0     0     0     0]
 [30138   195     4   175   280     2 30139     0]
 [30138    86     9  6627   229     2 30139     0]
 [30138    31   179     2 30139     0     0     0]
 [30138  5357 29927   196     2 30139     0     0]
 [30138  5444  5505     2 30139     0     0     0]
 [30138    69    97   151 30139     0     0     0]
 [30138  4699    21 20658     2 30139     0     0]
 [30138    69    97   151 30139     0     0     0]
 [30138    69    84    63   248     2 30139     0]], shape=(16, 8), dtype=int64)
tf.Tensor(
[[28543    36  8133   849     2 28544     0     0]
 [28543    17    20     7  1221     2 28544     0]
 [28543  2512    20    36   84

In [7]:
target_input = j[:, :-1]
target_output = j[:, 1:]

In [8]:
target_input

<tf.Tensor: shape=(16, 7), dtype=int64, numpy=
array([[28543,    36,  8133,   849,     2, 28544,     0],
       [28543,    17,    20,     7,  1221,     2, 28544],
       [28543,  2512,    20,    36,   849,     2, 28544],
       [28543,    18,    27,   143,   257,    33, 28544],
       [28543,    27,    22,   105,  8473,    33, 28544],
       [28543,   130,     8,    12,   578,     2, 28544],
       [28543,   146,    48,     2, 28544,     0,     0],
       [28543,    14,   123,   190,   269,     2, 28544],
       [28543,    17,    20,     7,   740,   225,     2],
       [28543,   146,    15,    65,   338,     2, 28544],
       [28543,  2249,     2, 28544,     0,     0,     0],
       [28543,    11,   413,    96,  4656,     2, 28544],
       [28543,    94,   128,   177, 28544,     0,     0],
       [28543,   186,     8,    12,   125, 13481,     2],
       [28543,    94,   128,   177, 28544,     0,     0],
       [28543,    94,   113,    89,   403,     2, 28544]])>

In [9]:
target_output

<tf.Tensor: shape=(16, 7), dtype=int64, numpy=
array([[   36,  8133,   849,     2, 28544,     0,     0],
       [   17,    20,     7,  1221,     2, 28544,     0],
       [ 2512,    20,    36,   849,     2, 28544,     0],
       [   18,    27,   143,   257,    33, 28544,     0],
       [   27,    22,   105,  8473,    33, 28544,     0],
       [  130,     8,    12,   578,     2, 28544,     0],
       [  146,    48,     2, 28544,     0,     0,     0],
       [   14,   123,   190,   269,     2, 28544,     0],
       [   17,    20,     7,   740,   225,     2, 28544],
       [  146,    15,    65,   338,     2, 28544,     0],
       [ 2249,     2, 28544,     0,     0,     0,     0],
       [   11,   413,    96,  4656,     2, 28544,     0],
       [   94,   128,   177, 28544,     0,     0,     0],
       [  186,     8,    12,   125, 13481,     2, 28544],
       [   94,   128,   177, 28544,     0,     0,     0],
       [   94,   113,    89,   403,     2, 28544,     0]])>

In [10]:
model = UTModel(4,
                128,
                4,
                512,
                32,
                optimizer="adam",
                learning_rate=3e-5)

model.mirrored_strategy = None

In [11]:
model.create_optimizer()
model.create_checkpoint_manager(data_dir)
model.create_summary_writer(data_dir)

Initializing model from scratch..........


(<tensorflow.python.ops.summary_ops_v2.ResourceSummaryWriter at 0x7fe2745a4390>,
 <tensorflow.python.ops.summary_ops_v2.ResourceSummaryWriter at 0x7fe2f7153390>)

In [14]:
model.fit([train_dataset, train_dataset])

(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Decoder MHA1 shape (16, 8, 128)
Decoder enc_output shape (16, 8, 128)
Executing Decoder Call...............
Executing time
Decoder MHA1 shape (16, 8, 128)
Decoder enc_output shape (16, 8, 128)
Executing Decoder Call...............
Executing time
Decoder MHA1 shape (16, 8, 128)
Decoder enc_output shape (16, 8, 128)
Executing Decoder Call...............
Executing time
Decoder MHA1 shape (16, 8, 128)
Decoder enc_output shape (16, 8, 128)
Mini Batch Loss :-  tf.Tensor(8.983512, shape=(), dtype=float32)
Step 0 Train_Loss 8.9835 Train_Accuracy 0.3077
Saving checkpoint for step 0 at /media/akanyaani/Disk2/git_repo/test_data/ckpt-3
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 12

(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Decoder MHA1 shape (16, 8, 128)
Decoder enc_output shape (16, 8, 128)
Executing Decoder Call...............
Executing time
Decoder MHA1 shape (16, 8, 128)
Decoder enc_output shape (16, 8, 128)
Executing Decoder Call...............
Executing time
Decoder MHA1 shape (16, 8, 128)
Decoder enc_output shape (16, 8, 128)
Executing Decoder Call...............
Executing time
Decoder MHA1 shape (16, 8, 128)
Decoder enc_output shape (16, 8, 128)
Mini Batch Loss :-  tf.Tensor(8.85766, shape=(), dtype=float32)
(16, 8)
(16, 8)
Final encoder embedding :-  (16, 8, 128)
Executing time
Executing time
Executing time
Executing time

Final Decoder embedding :-  (16, 8, 128)
Executing Decoder Call...............
Executing time
Decoder MHA1 shape (16, 8, 128)
Decoder enc_output shape (16, 8, 128)
Exe

InvalidArgumentError: In[0] mismatch In[1] shape: 8 vs. 7: [16,4,8,8] [16,4,7,32] 0 0 [Op:BatchMatMulV2] name: ut_model/decoder/encoder_0/decoder_layer/multi_head_attention_2/MatMul/

In [ ]:
a = tf.constant([[1]], tf.int32)

In [ ]:
tf.tile(a, [32, 10])