In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import tensorflow_datasets as tfds
import tensorflow as tf

import time
import numpy as np
import matplotlib.pyplot as plt

from ut_model import *
from data_pipeline import input_fn

In [3]:
tf.__version__

'2.1.0'

In [4]:
data_dir = "/media/akanyaani/Disk2/git_repo/test_data"

In [5]:
train_dataset, test_dataset = input_fn(batch_size=16)

#train_dataset = np.random.randint(low=0,high=30000,size=(10,32, 48))

In [6]:
for i, j in train_dataset:
    print(i)
    print(j)
    break

tf.Tensor(
[[30138    69    97   151 30139     0     0     0]
 [30138     7  1844  2791     2 30139     0     0]
 [30138    69    97   151 30139     0     0     0]
 [30138    69    97   151 30139     0     0     0]
 [30138    23    48   162    49 14799     2 30139]
 [30138   333     2 30139     0     0     0     0]
 [30138 10829 10823   216 30139     0     0     0]
 [30138    69 24228 29979    63   363     2 30139]
 [30138   164  2350  1029 10114     2 30139     0]
 [30138     9     4   105   453   135     2 30139]
 [30138     3   512     8    57  3812     2 30139]
 [30138    96  2504    17  1508    28 30139     0]
 [30138    56     8     9  5478  2070     2 30139]
 [30138    69    97   151 30139     0     0     0]
 [30138   365     2 30139     0     0     0     0]
 [30138   131 16328    16  1230    34 30139     0]], shape=(16, 8), dtype=int64)
tf.Tensor(
[[28543    94   128   177 28544     0     0     0]
 [28543     3  2263  2604     2 28544     0     0]
 [28543    94   128   177 2854

In [7]:
target_input = j[:, :-1]
target_output = j[:, 1:]

In [8]:
target_input

<tf.Tensor: shape=(16, 7), dtype=int64, numpy=
array([[28543,   627,  3751,  4090,   276, 28544,     0],
       [28543,    11,    50, 22138,     2, 28544,     0],
       [28543,    18,   186,     8,    12, 12201,     2],
       [28543,   127,     1,   212,    79,  6170,     2],
       [28543,    54,    22,  3093,  7676,     2, 28544],
       [28543,   146,    48,     2, 28544,     0,     0],
       [28543,   146,    48,     2, 28544,     0,     0],
       [28543,    94,   128,   177, 28544,     0,     0],
       [28543,    11,   510,  4866,     2, 28544,     0],
       [28543,    94,   128,   177, 28544,     0,     0],
       [28543,    19,     8,    12,  3716,     2, 28544],
       [28543,    11,    84,  1536,    40,     2, 28544],
       [28543,   106,   105,  4602,     2, 28544,     0],
       [28543,   635,     1,  2158,   714, 28544,     0],
       [28543,     4,    36,    50,    10,  4534,     2],
       [28543,    17,  5404,    34,   411,  5878,     2]])>

In [9]:
target_output

<tf.Tensor: shape=(16, 7), dtype=int64, numpy=
array([[  627,  3751,  4090,   276, 28544,     0,     0],
       [   11,    50, 22138,     2, 28544,     0,     0],
       [   18,   186,     8,    12, 12201,     2, 28544],
       [  127,     1,   212,    79,  6170,     2, 28544],
       [   54,    22,  3093,  7676,     2, 28544,     0],
       [  146,    48,     2, 28544,     0,     0,     0],
       [  146,    48,     2, 28544,     0,     0,     0],
       [   94,   128,   177, 28544,     0,     0,     0],
       [   11,   510,  4866,     2, 28544,     0,     0],
       [   94,   128,   177, 28544,     0,     0,     0],
       [   19,     8,    12,  3716,     2, 28544,     0],
       [   11,    84,  1536,    40,     2, 28544,     0],
       [  106,   105,  4602,     2, 28544,     0,     0],
       [  635,     1,  2158,   714, 28544,     0,     0],
       [    4,    36,    50,    10,  4534,     2, 28544],
       [   17,  5404,    34,   411,  5878,     2, 28544]])>

In [10]:
model = UTModel(4,
                128,
                4,
                512,
                32,
                optimizer="adam",
                learning_rate=3e-5)

model.mirrored_strategy = None

In [11]:
model.create_optimizer()
model.create_checkpoint_manager(data_dir)
model.create_summary_writer(data_dir)

Initializing model from scratch..........


(<tensorflow.python.ops.summary_ops_v2.ResourceSummaryWriter at 0x7efb700b5cd0>,
 <tensorflow.python.ops.summary_ops_v2.ResourceSummaryWriter at 0x7efae5e75050>)

In [12]:
model.fit([train_dataset, train_dataset])

(16, 8)
(16, 8)
Executing time
Executing time
Executing time
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  Tensor("Mean:0", shape=(), dtype=float32)
Executing time
Executing time
Executing time
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  Tensor("Mean:0", shape=(), dtype=float32)
Step 0 Train_Loss 10.3732 Train_Accuracy 0.0000
Saving checkpoint for step 0 at /media/akanyaani/Disk2/git_repo/test_data/ckpt-1
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 10 Train_Loss 10.2491 

(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 360 Train_Loss 8.4483 Train_Accuracy 0.1684
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 370 Train_Loss 8.3628 Train_Accuracy 0.1584
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 380 Train_Loss 8.0326 Train_Accuracy 0.2000
(16, 8)
(16, 8)
(16, 8)
(16, 7)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 390 Train_Loss 8.1296 Train_Accuracy 0.1702
(16, 7)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 400 Train_Loss 7.9453 Train_Accuracy 0.1975
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16

(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 760 Train_Loss 6.2854 Train_Accuracy 0.1928
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 770 Train_Loss 5.9850 Train_Accuracy 0.1905
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 780 Train_Loss 6.2541 Train_Accuracy 0.1818
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 790 Train_Loss 6.3121 Train_Accuracy 0.1720
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 800 Train_Loss 6.0554 Train_Accuracy 0.1882
(16

(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1150 Train_Loss 4.8691 Train_Accuracy 0.1905
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1160 Train_Loss 5.1930 Train_Accuracy 0.1720
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(15, 8)
(15, 8)
(16, 8)
(16, 8)
Step 1170 Train_Loss 4.6565 Train_Accuracy 0.1975
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1180 Train_Loss 4.9645 Train_Accuracy 0.1798
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1190 Train_Loss 4.9221 Train_Accuracy 0.1860
(16, 8)
(16, 8

(16, 8)
(16, 8)
Step 1540 Train_Loss 4.4688 Train_Accuracy 0.2527
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1550 Train_Loss 4.5871 Train_Accuracy 0.2333
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1560 Train_Loss 4.6657 Train_Accuracy 0.3187
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1570 Train_Loss 4.1078 Train_Accuracy 0.3086
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1580 Train_Loss 4.9045 Train_Accuracy 0.2947
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 7)
(16, 8)
(16, 8)
(16, 8

(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1940 Train_Loss 4.4109 Train_Accuracy 0.3187
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1950 Train_Loss 3.7936 Train_Accuracy 0.3187
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1960 Train_Loss 4.2220 Train_Accuracy 0.3229
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1970 Train_Loss 4.0847 Train_Accuracy 0.2935
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 1980 Train_Loss 3.1203 Train_Accuracy 0.3684
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8

(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 2330 Train_Loss 3.2186 Train_Accuracy 0.5000
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(15, 8)
(15, 8)


In [13]:
a = tf.constant([[1]], tf.int32)

In [14]:
tf.tile(a, [32, 10])

<tf.Tensor: shape=(32, 10), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1,