In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import tensorflow_datasets as tfds
import tensorflow as tf

import time
import numpy as np
import matplotlib.pyplot as plt

from ut_model import *
from data_pipeline import input_fn

In [3]:
tf.__version__

'2.3.0'

In [4]:
data_dir = "/media/akanyaani/Disk2/git_repo/test_data"

In [5]:
train_dataset, test_dataset = input_fn(batch_size=16)

#train_dataset = np.random.randint(low=0,high=30000,size=(10,32, 48))

In [6]:
for i, j in train_dataset:
    print(i)
    print(j)
    break

tf.Tensor(
[[30138    22     5  1443    13  3582    28 30139]
 [30138     8    31 14975     2 30139     0     0]
 [30138    13  1083    12    32 12219     2 30139]
 [30138    20    49    48   727    28 30139     0]
 [30138 27337   283    13   141  2251     2 30139]
 [30138     3   346     8  1005     2 30139     0]
 [30138     7     5     8   683 25379     2 30139]
 [30138     7   637    37   819     2 30139     0]
 [30138    69    97   151 30139     0     0     0]
 [30138  2213  6583  3999  7655     2 30139     0]
 [30138  1049     3   390 26456    28 30139     0]
 [30138   293 22263   307 30139     0     0     0]
 [30138     6     3   346     8   238     2 30139]
 [30138  3742    38  8156     2 30139     0     0]
 [30138    69    97   151 30139     0     0     0]
 [30138  1287    31   197     2 30139     0     0]], shape=(16, 8), dtype=int64)
tf.Tensor(
[[28543   147    67    15  1048  5128    33 28544]
 [28543    19     8    12   315  3042     2 28544]
 [28543  1199    22    36  591

In [7]:
target_input = j[:, :-1]
target_output = j[:, 1:]

In [10]:
target_input

<tf.Tensor: shape=(16, 7), dtype=int64, numpy=
array([[28543,   147,    67,    15,  1048,  5128,    33],
       [28543,    19,     8,    12,   315,  3042,     2],
       [28543,  1199,    22,    36,  5912,     2, 28544],
       [28543,    57,    20,     9,   794,    33, 28544],
       [28543, 25697,    66,  3311,     2, 28544,     0],
       [28543,     3,   493,    13,  1047,     2, 28544],
       [28543,  1015,  9267,     2, 28544,     0,     0],
       [28543,     3,    97,  1284,     2, 28544,     0],
       [28543,    94,   128,   177, 28544,     0,     0],
       [28543,  1281,   104,   820,  8145,     2, 28544],
       [28543,    74,    16,   126, 14648,    33, 28544],
       [28543,   627, 20271,   276, 28544,     0,     0],
       [28543,     4,     3,   493,    13,   358,     2],
       [28543,  2222,    55,     9,  4760,   973,     2],
       [28543,    94,   128,   177, 28544,     0,     0],
       [28543,    17,   292,     7,   265,   151,     2]])>

In [11]:
target_output

<tf.Tensor: shape=(16, 7), dtype=int64, numpy=
array([[  147,    67,    15,  1048,  5128,    33, 28544],
       [   19,     8,    12,   315,  3042,     2, 28544],
       [ 1199,    22,    36,  5912,     2, 28544,     0],
       [   57,    20,     9,   794,    33, 28544,     0],
       [25697,    66,  3311,     2, 28544,     0,     0],
       [    3,   493,    13,  1047,     2, 28544,     0],
       [ 1015,  9267,     2, 28544,     0,     0,     0],
       [    3,    97,  1284,     2, 28544,     0,     0],
       [   94,   128,   177, 28544,     0,     0,     0],
       [ 1281,   104,   820,  8145,     2, 28544,     0],
       [   74,    16,   126, 14648,    33, 28544,     0],
       [  627, 20271,   276, 28544,     0,     0,     0],
       [    4,     3,   493,    13,   358,     2, 28544],
       [ 2222,    55,     9,  4760,   973,     2, 28544],
       [   94,   128,   177, 28544,     0,     0,     0],
       [   17,   292,     7,   265,   151,     2, 28544]])>

In [12]:
model = UTModel(4,
                128,
                4,
                512,
                32,
                optimizer="adam",
                learning_rate=3e-5)

model.mirrored_strategy = None

In [13]:
model.create_optimizer()
model.create_checkpoint_manager(data_dir)
model.create_summary_writer(data_dir)

Initializing model from scratch..........


(<tensorflow.python.ops.summary_ops_v2.ResourceSummaryWriter at 0x7fd5595159d0>,
 <tensorflow.python.ops.summary_ops_v2.ResourceSummaryWriter at 0x7fd4b0433350>)

In [14]:
model.fit([train_dataset, train_dataset])

Instructions for updating:
use `tf.profiler.experimental.start` instead.


Instructions for updating:
use `tf.profiler.experimental.start` instead.


(16, 8)
(16, 8)
Executing time
Executing time
Executing time
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  Tensor("Mean:0", shape=(), dtype=float32)
Executing time
Executing time
Executing time
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  Tensor("Mean:0", shape=(), dtype=float32)
Step 0 Train_Loss 10.3540 Train_Accuracy 0.0000
Instructions for updating:
use `tf.profiler.experimental.stop` instead.


Instructions for updating:
use `tf.profiler.experimental.stop` instead.


Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.


Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.


Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.


Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.


Saving checkpoint for step 0 at /media/akanyaani/Disk2/git_repo/test_data/ckpt-1
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 10 Train_Loss 10.2546 Train_Accuracy 0.0213
(16, 8)
(16, 7)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 20 Train_Loss 10.1488 Train_Accuracy 0.1932
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 30 Train_Loss 10.1061 Train_Accuracy 0.1739
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 40 Train_Loss 10.0642 Train_Accuracy 0.1702
(16, 7)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16

(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 7)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 400 Train_Loss 7.9797 Train_Accuracy 0.1978
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 410 Train_Loss 8.0629 Train_Accuracy 0.1809
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 420 Train_Loss 7.9095 Train_Accuracy 0.1889
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 7)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 430 Train_Loss 7.8199 Train_Accuracy 0.2353
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 7)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 440 Train_Loss 7.7685 Train_Acc

(16, 8)
(16, 8)
Step 790 Train_Loss 6.3811 Train_Accuracy 0.2637
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 800 Train_Loss 6.1873 Train_Accuracy 0.2708
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 810 Train_Loss 6.2287 Train_Accuracy 0.2471
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 7)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 7)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 820 Train_Loss 5.8945 Train_Accuracy 0.3043
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
Step 830 Train_Loss 6.0530 Train_Accuracy 0.2556
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16, 8)
(16

KeyboardInterrupt: 

In [13]:
a = tf.constant([[1]], tf.int32)

In [14]:
tf.tile(a, [32, 10])

<tf.Tensor: shape=(32, 10), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1,