In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import tensorflow_datasets as tfds
import tensorflow as tf

import time
import numpy as np
import matplotlib.pyplot as plt

from ut_model import *
from data_pipeline import input_fn

In [3]:
tf.__version__

'2.3.0'

In [4]:
data_dir = "/disk/git_repo/test_data"

In [5]:
train_dataset, test_dataset = input_fn(batch_size=16)

#train_dataset = np.random.randint(low=0,high=30000,size=(10,32, 48))

In [6]:
for i, j in train_dataset:
    print(i)
    print(j)
    break

tf.Tensor(
[[30138    69    97   151 30139     0     0     0]
 [30138    51     8     3  1173     2 30139     0]
 [30138    69    97   151 30139     0     0     0]
 [30138    31   333     2 30139     0     0     0]
 [30138     3  2533     8   118 20181     2 30139]
 [30138    69    97   151 30139     0     0     0]
 [30138   179     2 30139     0     0     0     0]
 [30138 15377     8     9 20567  3402     2 30139]
 [30138     8  1657     2 30139     0     0     0]
 [30138   419  1339    28 30139     0     0     0]
 [30138     7     5     8   160   723    28 30139]
 [30138     8    72     5    14  5075     2 30139]
 [30138    73 20493     2 30139     0     0     0]
 [30138   327     8  2600   216 30139     0     0]
 [30138   179     2 30139     0     0     0     0]
 [30138    58  1641  1699     2 30139     0     0]], shape=(16, 8), dtype=int64)
tf.Tensor(
[[28543    94   128   177 28544     0     0     0]
 [28543    40     8    12     3   424     2 28544]
 [28543    94   128   177 2854

In [7]:
target_input = j[:, :-1]
target_output = j[:, 1:]

In [8]:
target_input

<tf.Tensor: shape=(16, 7), dtype=int64, numpy=
array([[28543,    94,   128,   177, 28544,     0,     0],
       [28543,    40,     8,    12,     3,   424,     2],
       [28543,    94,   128,   177, 28544,     0,     0],
       [28543,   146,    15,    18,   338,     2, 28544],
       [28543,  2625,    13,    18, 10953,     2, 28544],
       [28543,    94,   128,   177, 28544,     0,     0],
       [28543,   146,    48,     2, 28544,     0,     0],
       [28543, 13534,    13, 27772,     2, 28544,     0],
       [28543,    17,    87,   152,     2, 28544,     0],
       [28543,    29,    15,    99,     5,   174,    33],
       [28543,    27,    13,     9,   539,    33, 28544],
       [28543,    18,    15,  4529,     2, 28544,     0],
       [28543,   103,     3,  5788,     2, 28544,     0],
       [28543,    40,     8,    12,  2710,     2, 28544],
       [28543,   146,    48,     2, 28544,     0,     0],
       [28543,    61,  4027,  1626,     2, 28544,     0]])>

In [9]:
target_output

<tf.Tensor: shape=(16, 7), dtype=int64, numpy=
array([[   94,   128,   177, 28544,     0,     0,     0],
       [   40,     8,    12,     3,   424,     2, 28544],
       [   94,   128,   177, 28544,     0,     0,     0],
       [  146,    15,    18,   338,     2, 28544,     0],
       [ 2625,    13,    18, 10953,     2, 28544,     0],
       [   94,   128,   177, 28544,     0,     0,     0],
       [  146,    48,     2, 28544,     0,     0,     0],
       [13534,    13, 27772,     2, 28544,     0,     0],
       [   17,    87,   152,     2, 28544,     0,     0],
       [   29,    15,    99,     5,   174,    33, 28544],
       [   27,    13,     9,   539,    33, 28544,     0],
       [   18,    15,  4529,     2, 28544,     0,     0],
       [  103,     3,  5788,     2, 28544,     0,     0],
       [   40,     8,    12,  2710,     2, 28544,     0],
       [  146,    48,     2, 28544,     0,     0,     0],
       [   61,  4027,  1626,     2, 28544,     0,     0]])>

In [10]:
model = None

In [11]:
model = UTModel(8,
                128,
                4,
                512,
                32,
                optimizer="adam",
                learning_rate=3e-5)

model.mirrored_strategy = None

In [12]:
model.create_optimizer()
model.create_checkpoint_manager(data_dir)
model.create_summary_writer(data_dir)

Initializing model from scratch..........


(<tensorflow.python.ops.summary_ops_v2.ResourceSummaryWriter at 0x7f259860e590>,
 <tensorflow.python.ops.summary_ops_v2.ResourceSummaryWriter at 0x7f25987a3b50>)

In [13]:
model.fit([train_dataset, train_dataset])

Instructions for updating:
use `tf.profiler.experimental.start` instead.


Instructions for updating:
use `tf.profiler.experimental.start` instead.


(16, 8)
(16, 7)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49821302 0.49841005 0.4982586  0.488994   0.4938305  0.49537155
  0.49392518 0.49392518]
 [0.49892575 0.49441484 0.493638   0.49226758 0.5047968  0.4941997
  0.47973764 0.51316184]
 [0.50044835 0.49673003 0.49211997 0.49004427 0.49392518 0.49392518
  0.49392518 0.49392518]
 [0.5006693  0.5037211  0.49198228 0.48500985 0.488779   0.4960467
  0.47735137

Instructions for updating:
use `tf.profiler.experimental.stop` instead.


Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.


Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.


Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.


Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.


Saving checkpoint for step 0 at /disk/git_repo/test_data/ckpt-1
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49766752 0.49771985 0.49862003 0.49227908 0.49139166 0.49705803
  0.4787757  0.49387464]
 [0.49783966 0.49635348 0.49660343 0.49138615 0.49019724 0.4962426
  0.47911784 0.49387464]
 [0.49946526 0.5027605  0.49496597 0.485543   0.49124485 0.49387464
  0.49387464 0.49387464]
 [0.50152975 0.

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4995025  0.49061328 0.50133675 0.49298263 0.49581748 0.4944543
  0.49375907 0.49375907]
 [0.49876305 0.49943623 0.48667055 0.48842537 0.49714306 0.4919917
  0.49375907 0.49375907]
 [0.4987799  0.50139695 0.49424705 0.4901899  0.4946731  0.4913911
  0.49375907 0.49375907]
 [0.498741   0.49225926 0.49341306 0.48832154 0.49126032 0.49375907
  0.49375907 

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.5005136  0.4899481  0.4963389  0.4883321  0.4857923  0.49686196
  0.48332512 0.5106326 ]
 [0.5015479  0.49053037 0.49571207 0.48539954 0.49546713 0.48976392
  0.47862315 0.4936481 ]
 [0.49971068 0.49525177 0.4962851  0.4944202  0.49230874 0.4936481
  0.4936481  0.4936481 ]
 [0.49828643 0.4955771  0.49830067 0.48895967 0.4909267  0.49613354
  0.4784468

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4986741  0.4981164  0.49489015 0.4879318  0.49352184 0.49352184
  0.49352184 0.49352184]
 [0.5009121  0.5120645  0.49167714 0.48839176 0.4972496  0.49396202
  0.47887695 0.49352184]
 [0.4991612  0.49668285 0.49096113 0.4887802  0.49529845 0.49506378
  0.48052138 0.49352184]
 [0.4975171  0.49021384 0.49183917 0.4972722  0.49004763 0.49438623
  0.476286

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4968948  0.4965451  0.49005497 0.48627177 0.487611   0.48765567
  0.4818074  0.51044106]
 [0.49824333 0.49842593 0.49102142 0.4853097  0.495943   0.49292353
  0.49338636 0.49338636]
 [0.49773046 0.4976564  0.49045599 0.4877265  0.49107087 0.49401414
  0.47589162 0.5122407 ]
 [0.49792758 0.5005605  0.49053696 0.48757398 0.48854336 0.49428976
  0.478980

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4987059  0.49660337 0.49244827 0.49097705 0.49059927 0.49325868
  0.49325868 0.49325868]
 [0.49822178 0.5058301  0.4964537  0.48676026 0.4885537  0.49484065
  0.47770137 0.49325868]
 [0.5019915  0.49072236 0.48803368 0.48753878 0.4952779  0.49115098
  0.49325868 0.49325868]
 [0.49641985 0.4902842  0.49438408 0.49291715 0.49437806 0.49683243
  0.478630

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4996738  0.4896382  0.48764014 0.4900079  0.48921096 0.49687514
  0.47883528 0.49315268]
 [0.49882522 0.50158596 0.48590964 0.4871208  0.49172235 0.49225464
  0.49315268 0.49315268]
 [0.4988354  0.4893822  0.49037173 0.4927451  0.4857382  0.48348084
  0.47581545 0.50887245]
 [0.50024813 0.5018503  0.49446857 0.48659444 0.48944524 0.49504268
  0.476079

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4986772  0.49089292 0.49657536 0.48592055 0.4925712  0.49301216
  0.49305448 0.49305448]
 [0.5007675  0.49358156 0.4952028  0.48997676 0.49305448 0.49305448
  0.49305448 0.49305448]
 [0.4974884  0.4938695  0.48956504 0.48413008 0.49258956 0.49429062
  0.47887564 0.49305448]
 [0.497999   0.494481   0.49619213 0.49126205 0.4942043  0.49447766
  0.477799

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49683395 0.4961414  0.4966498  0.49050978 0.49296165 0.49296165
  0.49296165 0.49296165]
 [0.4967833  0.49673462 0.48735353 0.49037477 0.49315047 0.49120182
  0.48353273 0.51161   ]
 [0.49977407 0.5019721  0.49070284 0.4952986  0.49030486 0.49296165
  0.49296165 0.49296165]
 [0.50051385 0.4958595  0.49745125 0.48353407 0.49091476 0.48758453
  0.483541

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49820048 0.5099925  0.4869751  0.49038544 0.49424535 0.49733034
  0.47818422 0.49288598]
 [0.49528533 0.49871165 0.49647334 0.48753455 0.48738202 0.49412653
  0.4793761  0.49288598]
 [0.4987059  0.49392158 0.49193215 0.48415443 0.4945154  0.49143633
  0.49288598 0.49288598]
 [0.4999286  0.4966744  0.4940529  0.5034549  0.48803166 0.49514627
  0.478346

Step 30 Train_Loss 10.0838 Train_Accuracy 0.1882
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49882117 0.5039699  0.49018073 0.48748723 0.48961985 0.4928126
  0.4928126  0.4928126 ]
 [0.49697718 0.49172372 0.49123582 0.48540023 0.49126402 0.4858781
  0.47708613 0.4928126 ]
 [0.49821368 0.49302036 0.48507848 0.48455873 0.48668677 0.494287
  0.4809268  0.4928126 ]
 [0.497812   0.5023858  0.4948301

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49803057 0.50417054 0.49448147 0.48623896 0.48769668 0.492758
  0.492758   0.492758  ]
 [0.4978407  0.49941    0.4932369  0.48517323 0.485918   0.4952016
  0.4773919  0.492758  ]
 [0.49848387 0.49683443 0.48624876 0.4919392  0.49015117 0.492758
  0.492758   0.492758  ]
 [0.49899915 0.49213243 0.49543872 0.48973808 0.492758   0.492758
  0.492758   0.49

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4992301  0.4886285  0.48544613 0.49056244 0.49039724 0.48273036
  0.47876292 0.51442677]
 [0.49857736 0.49320894 0.49479163 0.48525494 0.49269983 0.49051172
  0.49271494 0.49271494]
 [0.4970462  0.4968013  0.4934091  0.49291402 0.4907569  0.49271494
  0.49271494 0.49271494]
 [0.49399033 0.49771073 0.49330604 0.4866229  0.4891847  0.4932711
  0.4781499

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4985533  0.4915494  0.48908398 0.49178553 0.49096802 0.49267906
  0.49267906 0.49267906]
 [0.49769467 0.5010468  0.48968446 0.48848736 0.49278238 0.49602944
  0.47748548 0.49267906]
 [0.4967817  0.49821976 0.48785907 0.482762   0.49232954 0.49015117
  0.4802981  0.49267906]
 [0.49549016 0.4902645  0.49496683 0.49035737 0.48410767 0.4838417
  0.48187  

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4995654  0.5017765  0.49130958 0.48727003 0.49134445 0.49266523
  0.49266523 0.49266523]
 [0.4991142  0.49111077 0.49481392 0.49189752 0.49266523 0.49266523
  0.49266523 0.49266523]
 [0.49499026 0.49022233 0.4961609  0.49201012 0.48877075 0.49266523
  0.49266523 0.49266523]
 [0.49735457 0.48756197 0.4965092  0.4788958  0.49670586 0.4900554
  0.4834168

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.50149924 0.49497718 0.49258766 0.49504858 0.49458566 0.49149382
  0.49263814 0.49263814]
 [0.49786398 0.49641922 0.49553052 0.48222917 0.48708075 0.4890517
  0.4832271  0.51092774]
 [0.4977245  0.5029611  0.4888849  0.48502308 0.49064222 0.49340475
  0.47984928 0.49263814]
 [0.49870566 0.49552137 0.49799523 0.48695636 0.49591824 0.494335
  0.47871467 

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49681905 0.4958675  0.49823156 0.49668556 0.4900025  0.49266985
  0.49259615 0.49259615]
 [0.4960487  0.49436507 0.48963723 0.48946223 0.4926822  0.4901978
  0.49259615 0.49259615]
 [0.4998999  0.50213563 0.4939911  0.4896054  0.49163675 0.49259615
  0.49259615 0.49259615]
 [0.49661946 0.49893138 0.49629346 0.49140835 0.49581882 0.48966548
  0.4925961

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49773502 0.49046826 0.49586314 0.4901199  0.4925461  0.4925461
  0.4925461  0.4925461 ]
 [0.49728894 0.49844694 0.4880071  0.4868694  0.4945291  0.4914751
  0.4925461  0.4925461 ]
 [0.4984803  0.49284828 0.49187803 0.4897611  0.49021804 0.49347353
  0.47820914 0.4925461 ]
 [0.499156   0.48743913 0.4966632  0.5018437  0.49120596 0.49775234
  0.48210126

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49757743 0.4961424  0.49400866 0.4944855  0.48326954 0.4880752
  0.48065576 0.513377  ]
 [0.49650764 0.5020874  0.49068573 0.49384865 0.4918654  0.49112377
  0.49249232 0.49249232]
 [0.49545044 0.5024812  0.48949477 0.4895754  0.49472183 0.4907948
  0.49249232 0.49249232]
 [0.49703312 0.50248706 0.4932325  0.48738888 0.4912257  0.49249232
  0.49249232

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49654832 0.48958272 0.49580166 0.48640078 0.4924551  0.4924551
  0.4924551  0.4924551 ]
 [0.50008327 0.4946766  0.4924532  0.4916752  0.49241495 0.49838933
  0.4794482  0.5103537 ]
 [0.49817953 0.50091577 0.49419254 0.48739937 0.49147585 0.4924551
  0.4924551  0.4924551 ]
 [0.4988245  0.5020249  0.49285737 0.48411772 0.48786834 0.4949543
  0.47763598 

Step 60 Train_Loss 9.9024 Train_Accuracy 0.1882
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49847147 0.50208026 0.4916549  0.49302086 0.48730564 0.4913424
  0.4770585  0.49241334]
 [0.499235   0.48896104 0.49064162 0.48503128 0.4917357  0.49218315
  0.49241334 0.49241334]
 [0.49752712 0.4936423  0.49866036 0.48789096 0.48621562 0.48731118
  0.47726455 0.51038647]
 [0.4982467  0.49036    0.49036

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49717766 0.4971462  0.48706582 0.48895523 0.49415725 0.48446262
  0.48096243 0.5115136 ]
 [0.4971816  0.4978199  0.49732715 0.4876096  0.49139673 0.49553594
  0.47915298 0.4923645 ]
 [0.49536827 0.49088466 0.4881957  0.4918778  0.49245724 0.49396074
  0.47562745 0.5108008 ]
 [0.4982991  0.48744452 0.4918192  0.49058756 0.4887139  0.49374762
  0.476725

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.497986   0.4972229  0.49042714 0.48062757 0.4952953  0.49051318
  0.49229243 0.49229243]
 [0.49836007 0.49914667 0.4845374  0.48766872 0.4893661  0.49748588
  0.48219392 0.51143754]
 [0.49526608 0.48961803 0.48796237 0.4913843  0.49429533 0.488548
  0.47930703 0.5117707 ]
 [0.49663946 0.49057657 0.4930108  0.49362803 0.4873746  0.48997653
  0.47999352

Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49813953 0.49183813 0.49132264 0.4925975  0.49137646 0.48477077
  0.48195013 0.5105073 ]
 [0.49813148 0.4889598  0.48912385 0.49067253 0.4949608  0.48985675
  0.49223754 0.49223754]
 [0.4965344  0.50184196 0.49458846 0.4845813  0.4907228  0.49223754
  0.49223754 0.49223754]
 [0.49610022 0.49862325 0.49420035 0.48997092 0.49223754 0.49223754
  0.49223754 0.49223754]
 [0.4968688  0.48977605 0.49164557 0.49223754 0.49223754 0.49223754
  0.49223754 0.49223754]
 [0.49795702 0.49276704 0.49695557 0.48829275 0.49223754 0.49223754
  0.49223754 0.49223754]
 [0.4982     0.4968004  0.49050966 0.49059302 0.49223754 0.49223754
  0.49223754 0.49223754]
 [0.49709782 0.49639073 0.48923728 0.494367   0.49326432 0.4855984
  0.479657   0.509564  ]
 [0.49826416 0.502569   0.4936221  0.48704138 0.4901071  0.49223754
  0.49223754 0.49223754]
 [0.497468   0.5024906  0.49144423 0.48698303 0.490501

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4968602  0.49348828 0.4928304  0.48844153 0.48924989 0.49369553
  0.47806507 0.49218094]
 [0.49635077 0.49051356 0.4891636  0.48728776 0.48752132 0.48512658
  0.4812023  0.51131725]
 [0.49777094 0.49804276 0.4882988  0.4832045  0.4967145  0.4926396
  0.48124066 0.51331466]
 [0.49736324 0.4999336  0.49159923 0.4894284  0.49323863 0.49080405
  0.4921809

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4988957  0.49472916 0.49742576 0.48501748 0.48302433 0.49528417
  0.47618628 0.49213272]
 [0.49645665 0.5068004  0.49294692 0.48223412 0.49217102 0.49646235
  0.48481497 0.51077247]
 [0.4952149  0.49174124 0.49117726 0.4888481  0.49213272 0.49213272
  0.49213272 0.49213272]
 [0.49679652 0.49093142 0.4938369  0.48792884 0.49213272 0.49213272
  0.492132

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49768677 0.49600887 0.49034646 0.4931361  0.490529   0.49207082
  0.49207082 0.49207082]
 [0.4956749  0.49245718 0.483317   0.4887319  0.48447314 0.48907247
  0.47806078 0.49207082]
 [0.49681193 0.4964916  0.49045908 0.48096403 0.4921962  0.4915922
  0.49207082 0.49207082]
 [0.49731654 0.49667415 0.48776752 0.4855869  0.49140593 0.49482197
  0.4806165

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4963124  0.49166384 0.48925146 0.49053434 0.49020502 0.49200267
  0.49200267 0.49200267]
 [0.49692288 0.4946906  0.49110124 0.4933231  0.4915796  0.49198973
  0.49200267 0.49200267]
 [0.4954185  0.48622137 0.48818922 0.49435553 0.48380288 0.4881399
  0.47925264 0.5105914 ]
 [0.49673316 0.49473098 0.48589063 0.49437895 0.48781028 0.49200267
  0.4920026

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49811244 0.4930733  0.49830785 0.4903194  0.49376953 0.49260673
  0.49195188 0.49195188]
 [0.4944532  0.49166238 0.4916088  0.4892581  0.49195188 0.49195188
  0.49195188 0.49195188]
 [0.49694708 0.4957383  0.49134594 0.48098734 0.4915789  0.4941122
  0.482731   0.5103289 ]
 [0.4995549  0.49241728 0.49216565 0.4851616  0.49185687 0.4903241
  0.49195188

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4972218  0.4980679  0.48953035 0.48762506 0.48388755 0.49579537
  0.47686607 0.49188104]
 [0.49766764 0.49436525 0.4915028  0.49010628 0.48795635 0.48992446
  0.49188104 0.49188104]
 [0.4963789  0.5015331  0.49197242 0.48560494 0.48973128 0.49188104
  0.49188104 0.49188104]
 [0.49584803 0.48913097 0.4911811  0.49178553 0.4907293  0.49188104
  0.491881

Step 90 Train_Loss 9.8023 Train_Accuracy 0.1798
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49845672 0.49332485 0.49512923 0.489992   0.49181804 0.49181804
  0.49181804 0.49181804]
 [0.4971555  0.49555287 0.48760918 0.48351097 0.5048954  0.4933026
  0.47992077 0.5116961 ]
 [0.5017468  0.50074303 0.48788404 0.48175776 0.483897   0.49399778
  0.47888318 0.49181804]
 [0.4944871  0.4887877  0.48870

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49669626 0.4917674  0.494316   0.48850536 0.49177364 0.49177364
  0.49177364 0.49177364]
 [0.4977535  0.49942225 0.49267265 0.4877328  0.49034154 0.49177364
  0.49177364 0.49177364]
 [0.49594533 0.4960927  0.4884361  0.48260587 0.48087597 0.49537694
  0.47730106 0.49177364]
 [0.49695963 0.4896889  0.4979053  0.48357967 0.48842126 0.48374134
  0.471566

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49644506 0.5000224  0.49242145 0.49314052 0.49020743 0.4986117
  0.47878495 0.51042235]
 [0.4955476  0.49903056 0.48934132 0.4910181  0.4930235  0.49018124
  0.48000556 0.5110454 ]
 [0.49862057 0.48720625 0.49533474 0.4887932  0.4917447  0.4917447
  0.4917447  0.4917447 ]
 [0.49834988 0.49560907 0.49439293 0.4901104  0.48427346 0.49317965
  0.4806519 

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4976215  0.4989788  0.492376   0.48775536 0.48739716 0.4947161
  0.47804987 0.4917376 ]
 [0.49720052 0.4934669  0.49136525 0.49289003 0.48958802 0.4896795
  0.47933418 0.4917376 ]
 [0.49533078 0.49499243 0.49185854 0.4914087  0.4916338  0.4917376
  0.4917376  0.4917376 ]
 [0.49877113 0.4993886  0.4925228  0.48344272 0.48968524 0.4917376
  0.4917376  0

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49782664 0.49651036 0.49355844 0.48947734 0.49361953 0.49138176
  0.49174556 0.49174556]
 [0.4936049  0.49071723 0.49376297 0.48917285 0.49174556 0.49174556
  0.49174556 0.49174556]
 [0.4977788  0.4890785  0.48970273 0.4868591  0.48365125 0.49398115
  0.47711265 0.5107271 ]
 [0.49778518 0.49538502 0.49221802 0.48927116 0.4921933  0.48959276
  0.491745

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49496233 0.5030593  0.49225932 0.48610127 0.49115562 0.49176586
  0.49176586 0.49176586]
 [0.4964422  0.49099785 0.49438184 0.4857989  0.49176586 0.49176586
  0.49176586 0.49176586]
 [0.49742684 0.50188285 0.4850334  0.48367447 0.48284993 0.49349368
  0.47861245 0.49176586]
 [0.49550498 0.493156   0.48657346 0.48618698 0.49283457 0.48942336
  0.491765

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4967997  0.49176338 0.48641974 0.48713997 0.48992702 0.49182093
  0.47860274 0.51203024]
 [0.4991959  0.4884133  0.4953568  0.48207116 0.48648006 0.4925976
  0.47807816 0.49176937]
 [0.4953931  0.5014107  0.49336898 0.48630208 0.48823348 0.49176937
  0.49176937 0.49176937]
 [0.49519902 0.49839523 0.49204248 0.48845717 0.49038246 0.49628252
  0.47761  

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49644583 0.4948277  0.48702362 0.49026257 0.49141595 0.49178058
  0.49178058 0.49178058]
 [0.49565384 0.4992906  0.48262104 0.4837162  0.4902087  0.48725107
  0.48034298 0.5094642 ]
 [0.49597254 0.49824262 0.49464843 0.48923922 0.48988646 0.49200347
  0.49178058 0.49178058]
 [0.49661547 0.49886853 0.4922478  0.48580992 0.49055618 0.49178058
  0.491780

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49511367 0.4992045  0.49089038 0.5003185  0.49517703 0.49139488
  0.47728443 0.49181402]
 [0.49739462 0.5068876  0.48455128 0.48643672 0.4926788  0.49032566
  0.49181402 0.49181402]
 [0.49611548 0.49130142 0.49172598 0.48834127 0.48891073 0.49279293
  0.4759428  0.49181402]
 [0.4964511  0.50274026 0.49354914 0.4932963  0.4914265  0.4981393
  0.4811634

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49714452 0.5023544  0.4930117  0.485513   0.4889076  0.49184164
  0.49184164 0.49184164]
 [0.4968522  0.48949683 0.49652857 0.49303    0.4912113  0.49426183
  0.4760692  0.49184164]
 [0.49715194 0.49328882 0.48527056 0.4926412  0.49258927 0.48943776
  0.49184164 0.49184164]
 [0.49758816 0.49479967 0.49181193 0.4907209  0.49238062 0.4909736
  0.4918416

Step 120 Train_Loss 9.6378 Train_Accuracy 0.1839
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49856585 0.5048173  0.48692146 0.48689234 0.49538758 0.49011487
  0.49189985 0.49189985]
 [0.4962648  0.49061903 0.49463278 0.48950243 0.49189985 0.49189985
  0.49189985 0.49189985]
 [0.49711147 0.49533293 0.49025407 0.48532254 0.48876145 0.49155873
  0.49189985 0.49189985]
 [0.49389005 0.5011154  0.483

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4980442  0.49142954 0.48770612 0.4931609  0.4930781  0.4915567
  0.49195695 0.49195695]
 [0.49667367 0.49114838 0.49356017 0.49022105 0.49195695 0.49195695
  0.49195695 0.49195695]
 [0.49416378 0.4926319  0.4912608  0.4882686  0.49195695 0.49195695
  0.49195695 0.49195695]
 [0.49889833 0.49398893 0.49280965 0.48535064 0.4869759  0.4943717
  0.47592694

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4962702  0.49475133 0.49604058 0.49117962 0.48993018 0.4920025
  0.4920025  0.4920025 ]
 [0.49605596 0.49575037 0.4864387  0.48883146 0.4884131  0.49005702
  0.48064727 0.5098811 ]
 [0.4951467  0.49360687 0.49406987 0.4912017  0.49377006 0.49322632
  0.4920025  0.4920025 ]
 [0.4949779  0.4988993  0.49062768 0.48609975 0.4896417  0.4920025
  0.4920025 

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4966561  0.5008628  0.4920821  0.48598588 0.4904288  0.49204803
  0.49204803 0.49204803]
 [0.49775314 0.48945576 0.49100113 0.4938661  0.49221215 0.49005175
  0.47416523 0.51073784]
 [0.49805045 0.49594024 0.49521527 0.48985636 0.49204803 0.49204803
  0.49204803 0.49204803]
 [0.49585506 0.48570853 0.49416506 0.4870436  0.49204803 0.49204803
  0.492048

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49599943 0.50025845 0.49155465 0.48304734 0.49039346 0.49211776
  0.49211776 0.49211776]
 [0.49725953 0.48915333 0.49092475 0.49460065 0.48882827 0.49211776
  0.49211776 0.49211776]
 [0.4956263  0.48801687 0.49200088 0.48680952 0.48591504 0.49347365
  0.47868893 0.49211776]
 [0.4963133  0.49773437 0.4841374  0.49472883 0.4879609  0.4940618
  0.4836808

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49728966 0.4903089  0.4890851  0.4821769  0.4862463  0.489863
  0.4763158  0.49217921]
 [0.49618208 0.4909243  0.49268445 0.4907138  0.49186978 0.49396247
  0.47504646 0.51078606]
 [0.49787346 0.49134654 0.48667666 0.48999062 0.48991874 0.48831466
  0.49217921 0.49217921]
 [0.496595   0.4884925  0.48976177 0.48815614 0.4948776  0.48865354
  0.49217921

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4952327  0.4972814  0.49242896 0.48874453 0.4922208  0.4922208
  0.4922208  0.4922208 ]
 [0.49687874 0.49394298 0.49012917 0.48066363 0.48528802 0.49707702
  0.47742698 0.4922208 ]
 [0.49799043 0.49054465 0.48748258 0.4872342  0.48672205 0.48949265
  0.48249245 0.51208335]
 [0.49692896 0.4893556  0.48728412 0.48880765 0.5006516  0.4890623
  0.4798406 

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4984755  0.48893228 0.4941207  0.48422077 0.49377248 0.4917764
  0.49226406 0.49226406]
 [0.4935273  0.49747962 0.4900703  0.4929102  0.49345753 0.4914247
  0.49226406 0.49226406]
 [0.5000915  0.49295655 0.4979584  0.4916291  0.48872882 0.49226406
  0.49226406 0.49226406]
 [0.49629557 0.4950834  0.4937113  0.49036887 0.49226406 0.49226406
  0.49226406

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4992273  0.4895803  0.4917772  0.48884794 0.48704818 0.495979
  0.47667837 0.49231938]
 [0.4969816  0.5006895  0.49301276 0.48438329 0.49096268 0.49231938
  0.49231938 0.49231938]
 [0.49821663 0.4945572  0.49353004 0.4914729  0.49112916 0.49231938
  0.49231938 0.49231938]
 [0.49772528 0.49164924 0.49164033 0.48911044 0.48517367 0.49281892
  0.48324636

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.50044113 0.48945016 0.48606563 0.4854514  0.49167126 0.49290812
  0.48059165 0.5132024 ]
 [0.4962042  0.4905559  0.4975089  0.49471498 0.48877802 0.48894128
  0.4811507  0.5114443 ]
 [0.50056595 0.5001668  0.49401367 0.48715293 0.4898994  0.4921865
  0.49241138 0.49241138]
 [0.4971628  0.50350827 0.4917574  0.48710033 0.48809263 0.49241138
  0.4924113

Step 150 Train_Loss 9.3917 Train_Accuracy 0.2000
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4964806  0.48877403 0.4931434  0.4889664  0.4925305  0.4925305
  0.4925305  0.4925305 ]
 [0.49820238 0.49967536 0.4920875  0.48731685 0.49056807 0.4925305
  0.4925305  0.4925305 ]
 [0.49740088 0.49237943 0.4877767  0.4862814  0.4873693  0.49635407
  0.477886   0.4925305 ]
 [0.49593762 0.4954605  0.49560

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49785525 0.49410066 0.49688262 0.48959538 0.49265963 0.49265963
  0.49265963 0.49265963]
 [0.49892002 0.49529913 0.49542516 0.487205   0.48288018 0.49498904
  0.4782863  0.49265963]
 [0.499974   0.49272352 0.49815184 0.4846271  0.48603892 0.49300134
  0.48258388 0.50997293]
 [0.49856535 0.4870948  0.49913847 0.4878148  0.48601595 0.49518287
  0.479297

ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4972267  0.5043387  0.48840654 0.48865935 0.4913683  0.4915589
  0.49281695 0.49281695]
 [0.49717653 0.49444428 0.4966037  0.49167767 0.49281695 0.49281695
  0.49281695 0.49281695]
 [0.49814522 0.4900465  0.4910465  0.48692876 0.48710904 0.49625587
  0.47790784 0.49281695]
 [0.49671346 0.49638444 0.48679924 0.48175123 0.48495847 0.48919898
  0.48131996 0.51129717]
 [

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49867517 0.49846074 0.4946363  0.48984492 0.49130556 0.49296314
  0.49296314 0.49296314]
 [0.49889523 0.4978413  0.493037   0.49246827 0.4938047  0.49357876
  0.49296314 0.49296314]
 [0.49615702 0.48751867 0.48486042 0.49081606 0.49337387 0.49277493
  0.49296314 0.49296314]
 [0.4982541  0.49990067 0.4895945  0.49365747 0.48373103 0.49948066
  0.483807

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49694237 0.50119185 0.49189097 0.48965752 0.49103108 0.49304962
  0.49304962 0.49304962]
 [0.49969584 0.5050296  0.49173835 0.49034888 0.49423727 0.49313778
  0.47932044 0.49304962]
 [0.49866787 0.49976432 0.4922787  0.4850878  0.49412152 0.49257794
  0.49304962 0.49304962]
 [0.4962782  0.48625574 0.48997504 0.489958   0.4943741  0.49287695
  0.493049

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49520415 0.50079596 0.48772985 0.48582882 0.48222342 0.49579948
  0.48022568 0.49310988]
 [0.49863017 0.4942382  0.4882099  0.48949134 0.49310988 0.49310988
  0.49310988 0.49310988]
 [0.49807197 0.4905169  0.49304092 0.4895172  0.4963815  0.49303803
  0.49310988 0.49310988]
 [0.4965257  0.48472694 0.49107477 0.4847473  0.49214244 0.49664593
  0.482332

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49772373 0.49578834 0.4987487  0.49164745 0.4969673  0.4947782
  0.47772613 0.49318817]
 [0.5004279  0.5017763  0.49111444 0.48704004 0.4908781  0.49318817
  0.49318817 0.49318817]
 [0.4989394  0.49991465 0.48559606 0.48636198 0.49214405 0.49318817
  0.49318817 0.49318817]
 [0.49937904 0.49584076 0.49358177 0.4853222  0.49189708 0.4933017
  0.4807926 

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4986051  0.49542353 0.49545974 0.48279935 0.49802637 0.49407506
  0.48048759 0.49330524]
 [0.49423727 0.49093804 0.49376354 0.4862236  0.48386106 0.4969015
  0.47671288 0.49330524]
 [0.497786   0.49404237 0.493292   0.49478316 0.49750543 0.49181706
  0.47885486 0.49330524]
 [0.49601302 0.494229   0.49118093 0.48067954 0.49656144 0.4967371
  0.4848764 

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4992116  0.489968   0.49209282 0.493106   0.49050084 0.49014065
  0.48177752 0.5122414 ]
 [0.49726665 0.5008055  0.49310085 0.48440477 0.49096292 0.49341357
  0.49341357 0.49341357]
 [0.49764875 0.49825054 0.48712736 0.48777834 0.49116638 0.4884784
  0.47596753 0.51080126]
 [0.5006236  0.48953333 0.4923056  0.49163058 0.48979583 0.49341357
  0.4934135

ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49778897 0.49779174 0.49120608 0.4932485  0.4921956  0.4935086
  0.4935086  0.4935086 ]
 [0.4968356  0.48786283 0.49414438 0.48501074 0.4858936  0.49802154
  0.4822594  0.51311904]
 [0.49611676 0.49466628 0.49328828 0.49177653 0.49716663 0.49238595
  0.4935086  0.4935086 ]
 [0.49809623 0.49767217 0.49246305 0.49124652 0.48977405 0.4961514
  0.47878855 0.4935086 ]
 [0

Step 180 Train_Loss 9.2999 Train_Accuracy 0.1798
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49938136 0.50127405 0.4953089  0.49038303 0.49571657 0.49126056
  0.49359614 0.49359614]
 [0.5000466  0.5018141  0.49224588 0.48554772 0.49176395 0.49359614
  0.49359614 0.49359614]
 [0.49627385 0.4888194  0.48479593 0.4902367  0.49643037 0.49385703
  0.48288506 0.51158917]
 [0.49410057 0.48995134 0.489

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49701092 0.498511   0.4926668  0.48695034 0.49147326 0.49370867
  0.49370867 0.49370867]
 [0.497131   0.49895352 0.49076152 0.4884066  0.49550357 0.4942174
  0.47669637 0.509608  ]
 [0.49565384 0.49844465 0.49564633 0.49447563 0.4900143  0.49370867
  0.49370867 0.49370867]
 [0.49920258 0.49609298 0.48860148 0.4917226  0.49417204 0.49127138
  0.4789518

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4997342  0.49670157 0.48633614 0.49112642 0.49193665 0.4916746
  0.47841898 0.49381632]
 [0.49849755 0.5029149  0.4895722  0.48974535 0.49412525 0.4932241
  0.49381632 0.49381632]
 [0.4969014  0.4921202  0.49075013 0.48979938 0.5008419  0.4920808
  0.49381632 0.49381632]
 [0.49678886 0.49234906 0.49405515 0.48896185 0.49583197 0.496183
  0.48052755 0.

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49699324 0.49541596 0.49415353 0.48995605 0.49585834 0.4965462
  0.47724327 0.493926  ]
 [0.49681765 0.49662206 0.49654597 0.49440354 0.4886988  0.4977648
  0.47977173 0.493926  ]
 [0.5005047  0.50081563 0.48544094 0.4897985  0.49743012 0.4947643
  0.493926   0.493926  ]
 [0.49740487 0.49601585 0.49607098 0.49083766 0.48925757 0.49664992
  0.47884396 

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49980915 0.49973175 0.49442708 0.49120152 0.49684167 0.49143213
  0.47966743 0.51063854]
 [0.4974069  0.50033593 0.49364063 0.4861422  0.49325046 0.4940177
  0.4940177  0.4940177 ]
 [0.49971464 0.49541947 0.4923011  0.4920225  0.4986178  0.49481148
  0.48124442 0.51244646]
 [0.50260586 0.49656677 0.49101934 0.48910487 0.49388552 0.49526164
  0.4940177

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49737987 0.4993816  0.49404818 0.48984092 0.49187317 0.49409822
  0.49409822 0.49409822]
 [0.49894103 0.48992732 0.49745908 0.491196   0.49409822 0.49409822
  0.49409822 0.49409822]
 [0.50038993 0.4979027  0.48752293 0.49347788 0.49167657 0.49409822
  0.49409822 0.49409822]
 [0.50003934 0.48856953 0.4960961  0.48607284 0.48953888 0.49077955
  0.478319

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49873185 0.4937757  0.49912748 0.49148518 0.49424914 0.49272954
  0.47882664 0.49417204]
 [0.5005613  0.5012825  0.49295145 0.48740768 0.48996836 0.49417204
  0.49417204 0.49417204]
 [0.50015193 0.49090132 0.4932653  0.49022347 0.49181205 0.49305865
  0.49417204 0.49417204]
 [0.49845454 0.4969465  0.49706995 0.48604164 0.4942216  0.49417204
  0.494172

Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(9.223343, shape=(), dtype=float32)
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.500587   0.4905477  0.49371704 0.48979333 0.4939666  0.49216825
  0.49422497 0.49422497]
 [0.49786067 0.4944435  0.49148574 0.49289143 0.48694378 0.4935366
  0.49422497 0.49422497]
 

Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(9.059599, shape=(), dtype=float32)
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
H

Halting prob :- tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]], shape=(16, 8), dtype=float32)
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Executing Decoder Call...............
Executing time
Mini Batch Loss :-  tf.Tensor(9.255316, shape=(), dtype=float32)
(16, 8)
(16, 8)
ACT 

Step 210 Train_Loss 9.1325 Train_Accuracy 0.2088
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49834692 0.49236694 0.49608213 0.484293   0.4933727  0.49835533
  0.4809112  0.49446857]
 [0.4997437  0.50069815 0.49168158 0.4871868  0.4916035  0.49446857
  0.49446857 0.49446857]
 [0.49963132 0.5039344  0.49297035 0.5016512  0.4965809  0.49426043
  0.49446857 0.49446857]
 [0.49452564 0.50045246 0.494

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.5000435  0.49647516 0.49172765 0.49515745 0.4928686  0.4945683
  0.4945683  0.4945683 ]
 [0.5004206  0.49747673 0.4887581  0.4859575  0.4897415  0.49450222
  0.4945683  0.4945683 ]
 [0.49820012 0.5004496  0.50022054 0.4897852  0.4892089  0.49120635
  0.4809073  0.51398224]
 [0.5013061  0.49547535 0.49591133 0.4852829  0.48850852 0.50073737
  0.4820987

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.5021032  0.4887909  0.49277514 0.48496622 0.49094084 0.4891903
  0.48345125 0.5140862 ]
 [0.50141364 0.48976678 0.48760828 0.4925059  0.49034014 0.49435458
  0.47920465 0.49466243]
 [0.49929142 0.49660146 0.4953922  0.49708554 0.49833295 0.4941661
  0.49466243 0.49466243]
 [0.4982953  0.49862903 0.49480638 0.49093148 0.49164924 0.49306914
  0.49466243

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4993739  0.50253    0.5011105  0.49433595 0.4915701  0.49471587
  0.49471587 0.49471587]
 [0.49842227 0.49801853 0.48870993 0.4865897  0.4969428  0.48774862
  0.48341757 0.51216173]
 [0.50066817 0.4910106  0.49903306 0.4892454  0.49042398 0.49789613
  0.48085257 0.49471587]
 [0.49774224 0.4973078  0.4936331  0.49418566 0.49147412 0.49604747
  0.479884

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49788824 0.49491048 0.49351835 0.49206823 0.49474066 0.4927486
  0.48324648 0.5118949 ]
 [0.49997294 0.48950043 0.49507207 0.4957457  0.4990244  0.49507084
  0.4947621  0.4947621 ]
 [0.49821976 0.4991175  0.48932877 0.49041218 0.49111837 0.49515057
  0.4947621  0.4947621 ]
 [0.49673358 0.50273097 0.49343488 0.48805004 0.49218556 0.4947621
  0.4947621 

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49950755 0.48991546 0.49662477 0.48903865 0.494147   0.4945227
  0.49480423 0.49480423]
 [0.5002453  0.50243    0.4936963  0.48917177 0.4929439  0.49480423
  0.49480423 0.49480423]
 [0.49714336 0.50122017 0.4950787  0.48747566 0.49314165 0.49480423
  0.49480423 0.49480423]
 [0.50107074 0.50292593 0.49636018 0.49417666 0.49022186 0.48932073
  0.4855111

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49818462 0.49530813 0.49701145 0.4903718  0.49644852 0.4869365
  0.4824484  0.51155674]
 [0.49743885 0.49807844 0.48631123 0.48780358 0.4933977  0.49771884
  0.47712368 0.49485454]
 [0.49603495 0.4984994  0.48841062 0.4935506  0.49070236 0.49485454
  0.49485454 0.49485454]
 [0.5005992  0.49790004 0.49972454 0.4863881  0.49807164 0.49454308
  0.4948545

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.5010453  0.49910942 0.49450234 0.49163702 0.48962346 0.49855912
  0.48051843 0.49493682]
 [0.49887517 0.49695438 0.49773526 0.4849505  0.49179935 0.48937735
  0.48482662 0.51429886]
 [0.49895185 0.49027997 0.49253014 0.49161342 0.4946301  0.49849606
  0.4808237  0.49493682]
 [0.49862477 0.5012362  0.49453726 0.48585004 0.49695173 0.49493682
  0.494936

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.4997324  0.50040627 0.49545178 0.4885305  0.48813537 0.4968383
  0.48199987 0.49502134]
 [0.50034255 0.49575529 0.4920922  0.48355612 0.49890044 0.49371624
  0.49502134 0.49502134]
 [0.5003048  0.49448952 0.48480213 0.48973304 0.49686196 0.4949392
  0.49502134 0.49502134]
 [0.49981993 0.50108624 0.48635015 0.4957444  0.49213406 0.49257016
  0.48144117

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.5011213  0.499132   0.4986235  0.49322292 0.49508095 0.49508095
  0.49508095 0.49508095]
 [0.50109595 0.5027223  0.49463803 0.4895195  0.49348062 0.49586278
  0.48171178 0.5136243 ]
 [0.5009207  0.49146363 0.4867307  0.48729476 0.4976948  0.493404
  0.49508095 0.49508095]
 [0.49949232 0.48900187 0.49570006 0.4963824  0.49213383 0.49100235
  0.4813419 

Step 240 Train_Loss 8.8597 Train_Accuracy 0.2716
(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49667352 0.49757233 0.4967657  0.49161422 0.49512753 0.49512753
  0.49512753 0.49512753]
 [0.49925867 0.50986755 0.48821422 0.48457536 0.49002314 0.4932293
  0.4836144  0.5130945 ]
 [0.49867707 0.49682254 0.49653333 0.49303928 0.49512753 0.49512753
  0.49512753 0.49512753]
 [0.49729827 0.5007434  0.4934

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.5002735  0.49903098 0.49559936 0.4966275  0.4938089  0.49520117
  0.49520117 0.49520117]
 [0.50151366 0.5009453  0.49436134 0.49321166 0.48945814 0.49738553
  0.48076352 0.49520117]
 [0.5001405  0.4956741  0.49362198 0.48760018 0.4923886  0.49796784
  0.4800677  0.49520117]
 [0.50042456 0.49554545 0.4895233  0.48521194 0.4897355  0.493011
  0.48170176

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.500556   0.4960382  0.49234745 0.49185714 0.50209326 0.49568334
  0.4803563  0.49529153]
 [0.4993691  0.49151373 0.48811966 0.49072632 0.49378893 0.49769917
  0.48195666 0.49529153]
 [0.50063246 0.50176066 0.49438676 0.48737767 0.49438184 0.49529153
  0.49529153 0.49529153]
 [0.49760848 0.50014055 0.49515575 0.4943583  0.5060506  0.49739957
  0.482393

(16, 8)
(16, 8)
ACT activated,,,,,,,,,,,,
Halting prob :- tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 8), dtype=float32)
Shape of input :- tf.Tensor([ 16   8 128], shape=(3,), dtype=int32)
Executing time
Halting prob :- tf.Tensor(
[[0.49988452 0.49544442 0.49546605 0.48816296 0.49551728 0.49555534
  0.49537835 0.49537835]
 [0.4983731  0.4937081  0.49170238 0.4910085  0.4951844  0.49326763
  0.48434353 0.51391995]
 [0.5015437  0.493514   0.49194616 0.48799348 0.50172484 0.49637762
  0.49537835 0.49537835]
 [0.49791813 0.49163523 0.4924861  0.49213567 0.50017124 0.49911916
  0.479830

KeyboardInterrupt: 

In [ ]:
a = tf.constant([[1]], tf.int32)

In [ ]:
tf.tile(a, [32, 10])